apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Kubeturbo.v1.charts.helm.k8s.io
  name: turbo-og
  namespace: kube-turbo
spec:
  targetNamespaces:
  - kube-turbo
