apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubeturbo-certified
  namespace: kube-turbo
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubeturbo-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
